// GENERATED-STYLE STUB, not generated by xcodegen: AetherfieldHost exists
// only so AetherfieldAUExtension has a container app to embed in (Apple's
// AUv3 packaging requirement). This app has no UI and is never intended to
// be used directly. Without any source, Xcode links no Mach-O binary at
// all, which builds and codesigns "successfully" (codesign does not
// require CFBundleExecutable to exist) but fails to install anywhere,
// device or simulator, with "is missing its bundle executable" -- see
// docs/testing.md's 2026-09-20 correction note and simulator-install
// finding. This is the minimal fix: delegates with no behavior, using the
// modern scene lifecycle solely so a real executable links and the host can
// launch without the legacy-lifecycle warning.
#import <UIKit/UIKit.h>

@interface AetherfieldHostAppDelegate : UIResponder <UIApplicationDelegate>
@end

@implementation AetherfieldHostAppDelegate
@end

@interface AetherfieldHostSceneDelegate : UIResponder <UIWindowSceneDelegate>
@property(strong, nonatomic) UIWindow *window;
@end

@implementation AetherfieldHostSceneDelegate
@end

int main(int argc, char *argv[]) {
  @autoreleasepool {
    return UIApplicationMain(argc, argv, nil,
                              NSStringFromClass([AetherfieldHostAppDelegate class]));
  }
}
