// GENERATED-STYLE STUB, not generated by xcodegen: AetherfieldHost exists
// only so AetherfieldAUExtension has a container app to embed in (Apple's
// AUv3 packaging requirement). This app has no UI and is never intended to
// be used directly. Without any source, Xcode links no Mach-O binary at
// all, which builds and codesigns "successfully" (codesign does not
// require CFBundleExecutable to exist) but fails to install anywhere,
// device or simulator, with "is missing its bundle executable" -- see
// docs/testing.md's 2026-09-20 correction note and simulator-install
// finding. This is the minimal fix: a delegate with no behavior, run
// without a scene manifest (legacy window-based lifecycle), so a real
// executable links.
#import <UIKit/UIKit.h>

@interface AetherfieldHostAppDelegate : UIResponder <UIApplicationDelegate>
@end

@implementation AetherfieldHostAppDelegate
@end

int main(int argc, char *argv[]) {
  @autoreleasepool {
    return UIApplicationMain(argc, argv, nil,
                              NSStringFromClass([AetherfieldHostAppDelegate class]));
  }
}
